### ISSUE TITLE
PLEASE COMMENT: Agree on namespace{} use

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#11]
We need to harmonize use of namespaces in the project (and in the future ones too). I suggest to adopt the following policy:
- all project-specific stuff belongs to global namespace . This includes classes/functions/... . 
- things which will be shared among the projects - belong to to a separate namespace (maybe 'hare', as Marcos has suggested), AND to a separate folder ('hare'?). In other words, ONLY stuff which is in the 'hare' folder, belongs to 'hare' namespace.

IF we adopt this policy, then for the time being MOST of the stuff is to be kept in global namespace; one possible exception for now is ASSERT macro (probably should be HAREASSERT or something), there will be a separate issue on it. WHEN we'll have another project AND see something which needs to be shared - we'll move it to hare folder AND namespace.

Marcos/DI, PLEASE COMMENT EVEN IF YOU AGREE WITH THE ABOVE

**Comment by divanchykhin** [comment]
Looking from my side... this is what I'm practically following for at least 50% (in a part of keeping staff in a global namespace), so what remains for me is to use separate namespaces for shareable staff (do I have any so far? - looks to be not). To mark up commonly used things (like those ASSERTs) is a good idea, and too many different namespaces as for me is a bit over-killing. So, in general, I would rather argue for NoBugs' proposal.

**Comment by marcosbracco** [comment]
I agree that for the time being MOST will be in the global. And only common shared code should be in namespace.
Namespace is usually a courtesy to whoever will try to reuse my code into some bigger projects (by a different team of people). This does not seem to be needed for this projects.

As for assert, I like HARE_ASSERT, as to make completely clear to whoever reads the code, it is OUR definition of assert.
