### ISSUE TITLE
Harmonize asserts 

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#12]
Suggestion re. asserts:
- make hare::Assert class (hare being a namespace, see issue #11) with all the assert data (const char\* file, int line, const char\* reason)
- make HAREASSERT() macro with syntax identical to assert(), but throwing hare::Assert instead of calling abort()
- put both of them to new /src/hare/ folder (see issue #11)
- use HAREASSERT in all the relevant places instead of both assert() and ASSERT()
- always catch it at topmost level in main(), printing all the available info

**Comment by nobugs-hare** [comment]
One good candidate to use as hare:Assert is current hare::AssertException from front/error.h

Note though that OTHER exceptions in front/error.h are project-specific, and as such do NOT belong to generic hare folder (neither to namespace, if we adopt the policy in issue #11)

**Comment by marcosbracco** [comment]
I agree with just one comment.
Calling abort while in 'development mode' is usually handy since Visual Studio will automatically go into debug breakpoint, preserving the stack, and making easier to find why the assertion failed.
While most ide can be configured to 'break on throw' for certain exception, this is harder to work nice.

So, I would propose to throw hare::Assert only in 'RELEASE' build, and continue to abort() on 'DEBUG' build.

**Comment by marcosbracco** [comment]
Or I can just stop being lazy and put my breakpoint inside HAREASSERT... :)

**Comment by nobugs-hare** [comment]
Last time I've checked, it was possible to make VS to stop on a C++ exception. 

In any case, I am against having that much different behaviour for Debug and Release builds (just because they should be "about the same"). So, I insist on making HARE_ASSERT throw exception in both Release and Debug. Adding something like 
#if defined(_WINDOWS) && defined(_DEBUG)
if IsDebuggerPresent()
    DebugBreak();
#endif
into exception-throwing function (before throwing the exception) is possible, but you need to discuss it with @divanchykhin .

**Comment by marcosbracco** [comment]
After some thinking, now I feel is better to always throw. As you mention having different behaviors is worst option. I will see how to properly configure VS to my needs.

**Comment by nobugs-hare** [comment]
closing (hare::Assert and HAREASSERT()/HAREASSERTM() added, STYLE-GUIDE updated)
