### ISSUE TITLE
PLEASE COMMENT: Formatting for IDLC

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#15]
Currently STYLE-GUIDE mentions printf(), and /back/ uses it, and /front/ uses std::iostream directly.

What about switching to https://github.com/cppformat/cppformat throughout the code (namely - to
print("Hello, {}!", "world"); 
syntax)? It is type-safe (unlike printf()), readable (unlike plaid std::iostream), has positional arguments (not that we need it now, but it is a nice-to-have feature, esp. for i18n), actively supported and so on...

Marcos/DI, PLEASE COMMENT EVEN IF YOU AGREE WITH IT.

**Comment by divanchykhin** [comment]
Well, as for me it's funny and might serve as a common denominator :)
If there are no immediate concerns/objections on using it, I can try it practically next week (well, I have less code to change than Marcos); hopefully I'll be ready to continue using it even after that, too (and I promise to share my experience anyway)

**Comment by marcosbracco** [comment]
I currently use std::iostream directly in /src/front, and mostly as debug output (tree dumps) because the process of 'appending to buffer' feels natural for it.
Probably /src/back (doing the real output) will take advantage of an stronger formatting library.
I say let's try it.

**Comment by nobugs-hare** [comment]
@marcosbracco : I take it that you're ok with switching to C++ Format library for text outputs (from direct use of std::iostream which you're currently using), so I will make an appropriate change to STYLE-GUIDE.md and will close the issue. If I didn't understood you correctly - please re-open the issue.
