### ISSUE TITLE
PLEASE COMMENT: decide on the way to #include 3rd-party libs

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#16]
Now as we have a 3rd-party lib (cppformat, which is supposed to show in your local copies too, if not - please open an issue), a question arises on the policy on "how to include and link 3rd-party libs for our project". Leaving aside linking for a moment, there is a question of "how to #include these?"

Option 1. "-I". Add /3rdparty/cppformat/cppformat to "-I" list, and #include it as simple <format.h>

Option 2. relative paths. use something like #include <../../....../<getting to /src/ level here>/3rdparty/cppformat/cppformat/format.h>

Option 3. Hide it within a "common" header. I.e. have something like /src/common_includes.h which everybody #includes, and which does either Option 1 or Option 2 within (probably Option 2 then). 

I tend to lean towards Option 3, but let's discuss it first.

@divanchykhin and @marcosbracco , please comment even if you agree.

**Comment by marcosbracco** [comment]
I don't have any special preference. Will vote option 3, seems simpler and cleaner.
