### ISSUE TITLE
Support for DISCRIMINATED-UNION

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#34]
I suggest to add support for DISCRIMINATED-UNION to IDL

Proposed syntax:

DISCRIMINATED-UNION(DISCRIMINANT=x) MyType {
    enum { Abc, Def, Ghi, Klm } x;//DISCRIMINANT MUST be an enum 
    string s WHEN-DISCRIMINANT x IN { Abc, Def };
    int i WHEN-DISCRIMINANT x == Abc; //mere synonym for 'x IN { Abc };'
   // expressions such as x == Abc || x == Def are NOT allowed
   int ii;//as there is no WHEN-DISCRIMINANT clause, it is "always present"
}

Notes on syntax: 
- if there are no objections, I suggest to adopt '-' for keywords in IDL instead of '_', spaces around '-' are NOT allowed. If we agree on it, it should mean that PUBLISHED_STRUCT should be replaced with PUBLISHED-STRUCT in IDL

Proposed mapping of DISCRIMINATED-UNION to idl_tree.h:
- add new Structure::TYPE = DISCRIMINATED_UNION
- add string Structure::discriminant; // contains DISCRIMINANT parameter, valid only for Structure::TYPE == DISCRIMINATED_UNION
- add vector<string> DataMember::whenDiscriminant; //valid only when Structure::TYPE is DISCRIMINATED_UNION

**Comment by marcosbracco** [comment]
I added basic support for such union, for easier discussion.
Added also support for unnamed enums `enum {...} x;` that where not previously supported.
However, enums without values assigned at each label are still not supported:
`enum { Abc, Def, Ghi, Klm } x;` currently not supported
as opossed to:
`enum { Abc=0, Def=1, Ghi=2, Klm=3 } x;` currently supported

Should I add support for such enums?

Output dump from sample:

|-Structure kind=IDL type=DISCRIMINATED_UNION name=MyType encAttrs=(  ) discr=x
| |-DataMember name='x'  { kind=ENUM name= enumValues=Abc=1,Def=2,Ghi=3,Klm=4 }
| |-DataMember name='s' whenDiscriminant='Abc,Def' { kind=PRIMITIVE name=string }
| |-DataMember name='i' whenDiscriminant='Abc' { kind=PRIMITIVE name=int }
| |-DataMember name='ii'  { kind=PRIMITIVE name=int }

Still missing to check discriminant name is same at DataMember level than at Struct level. And probably some more details.

Comments are welcome

**Comment by marcosbracco** [comment]
My only comment about the syntax is that the discriminant is stated two times, first at `DISCRIMINATED-UNION(DISCRIMINANT=x)` and then again at each member that needs it `int i WHEN-DISCRIMINANT x == Abc;`
And this seems redundant, maybe only one of the two is needed.

**Comment by nobugs-hare** [comment]
> Added also support for unnamed enums enum {...} x; that where not previously supported.

I suggest to drop unnamed enums at least for now, and use the same named-enum as before (changing sample IDL)

> However, enums without values assigned at each label are still not supported:
> enum { Abc, Def, Ghi, Klm } x; currently not supported
> Should I add support for such enums?

No, let's change the sample to include the values.

> My only comment about the syntax is that the discriminant is stated two times, first at DISCRIMINATED-UNION(DISCRIMINANT=x) and then again at each member that needs it int i WHEN-DISCRIMINANT x == Abc;
> And this seems redundant, maybe only one of the two is needed.

What about changing it to WHEN-DISCRIMINANT IS Abc and WHEN-DISCRIMINANT IN { Abc, Def }? Will also make less likely somebody trying to write an expression here.

**Comment by marcosbracco** [comment]
I have pushed all the changes commented above, below sample from **/src/front/idl/test/sample.idl**

```
DISCRIMINATED-UNION(DISCRIMINANT=x) MyType {
    enum TYPE { Abc = 1, Def = 2, Ghi = 3, Klm = 4 } x;
    string s WHEN-DISCRIMINANT IN { Abc, Def };
    int i WHEN-DISCRIMINANT == Abc;
   int ii;
};
```

I like it better, maybe changing keywords to `WHEN-DISCRIMINANT-IN` and `WHEN-DISCRIMINANT-IS` and droping the `==` will look nicer?

**Comment by nobugs-hare** [comment]
> I like it better, maybe changing keywords to WHEN-DISCRIMINANT-IN and WHEN-DISCRIMINANT-IS and droping the == will look nicer?

Yes, let's do it.
