### ISSUE TITLE
Consider streamlining work with lexer

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#35]
These yy_scan_string(), yy_create_buffer(), and yy_switch_to_buffer() look unnecessary at the first glance. What is the reason for using them (and if there is no reason, I suggest to remove them on "unnecessary entity" and "unnecessary dependency" basis). I've read that yy_create_buffer() is "sold" as a way to deal with include files, but honestly, I don't really see why it is necessary (as at least I myself done it without these). 

On the other hand - if we do need them - let's keep, so removing them is not a requirement as such, but is a question "do we really need this stuff?"

**Comment by marcosbracco** [comment]
That code with `yy_switch_to_buffer` is about being able to parse an string buffer as oposed to parse exclusively from a file.
Is only about being more generic and is the same as done internally by lexer code the first time we call it.
I will remove all of that.
