### ISSUE TITLE
Consider replacing FILE* with istream in lexer

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#36]
Is it really inevitable? We're using iostream for everything else, so making an exception for lexer makes it quite strange (using both FILE\* and iostream in the same executable is technically fine, but usually indicates unnecessary overhead). So - is it possible to change FILE\* to istream (it will also allow to get rid of those ugly #pragma warnings, which need to be addressed in any case, but getting rid of FILE\* is the best way of doing it)?

**Comment by marcosbracco** [comment]
Not sure.
Default lex is C only and only FILE.
But currently we are using flex / bison that have a lot of options. Maybe there is some option combination to allow flex work with isteram, and bison to play along.
I will dig a little some more

**Comment by nobugs-hare** [comment]
I'd rather not introduce an extra dependency on flex. What do you think about switching the rest of the project back to FILE\* from iostream, to make everything consistently FILE\* -based? cppformat seems to work with FILE\* the same way as with iostream...

**Comment by marcosbracco** [comment]
I was already using `FILE*` for `stderr` and `stdout` as the first arguments for cppformat `fmt::print`
I think I had misunderstood that style-guideline, so I had already switched to using `FILE*` everywhere. So I am ok with that.

The only real problem I used to have with `FILE*` is the lack of RIIA provided by `fstream`, but I have solved that using:
    `unique_ptr<FILE, int(*)(FILE*)> file(fopen(fileName.c_str(), "r"), &fclose);`

Quite ugly, but gets the job done.

While in general I like the buffer appending style of iostream, the exactly same thing can be done using std::string as buffer without any problem when talking about debug dumps, where sizes are small and performance is not even a concern.

**Comment by nobugs-hare** [comment]
Ok, I'll ask @divanchykhin , if he's ok with it - we'll switch to FILE\* throughout (using this RAAI trick of yours with unique_ptr<> ;-) ).

**Comment by nobugs-hare** [comment]
Ok, I will replace istream/ostream with FILE\* in STYLE-GUDE.

**Comment by nobugs-hare** [comment]
Changes committed, closing issue
