### ISSUE TITLE
Improve readability of delete semantics in parser_helper

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#37]
Code such as 

YYSTYPE createPublishableStruct(YYSTYPE token, YYSTYPE id)
{
    Structure\* yy = new Structure();

```
delete token;
yy->location = getLocationFromYyIdentifier(id);
yy->name = getNameFromYyIdentifier(id);
yy->declType = Structure::IDL;
yy->type = Structure::STRUCT;

return new YyPtr<Structure>(yy);
```

}

is very confusing. The main reason for confusion is that function getNameFromYyIdentifier() is (despite the get...() name(!)) also deletes it's parameter. It also makes reviewing the code very difficult: while all the create...() functions are supposed to delete ALL their YYKTYPE parameters, it is very unclear what is deleted and what is not.

Suggestion:
rename ALL the getSomethingFromSomethingElse() functions which also delete their input parameter to much more suitable getSomethingFromSomethingElseAndDelete(). So getNameFromYyIdentifier() should be renamed to getNameFroYyIdentifierAndDelete(), getArgumentList() - to getArgumentListAndDelete(). 

I also suggest to apply the same naming convention to functions such as makeDataMember() (which IMO should become makeDataMemberAndDelete()), and any other functions which delete their YYSTYPE parameters (if any).

**Comment by marcosbracco** [comment]
The implicit rule was that all functions that take an YYSTYPE parameter always deleted all of them or transferred the ownership to the returned pointer.
With the exception of `getLocationFromYyIdentifier` that does not delete the arguments, this rule applies to all of the functions called from parser and all of the helper functions.
But probably better to make it explicit at the function name.

**Comment by nobugs-hare** [comment]
Yes, it is double-better :). First, "get" implies constness unless otherwise specified, and second, as soon as you got one single exception - you need to distinguish very clearly between those-who-delete and those-who-don't
