### ISSUE TITLE
THE BIG ONE: parsing C++

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#40]
To make life of the developer-using-IDL easier, we need to be able to produce "mappings" right from target language. The first language on this list is C++.

What we need:
- to get mappings (equivalent to MAPPING in IDL) from C++ .h / .cpp
- names of the files, _and_ names structs/classes to be included, SHOULD be taken from IDL file (for example, as "MAPPING(Lang="C++") { FILE "abc.h" { CLASS XX; CLASS ZZ; } }
- these mappings MAYBE either "usual" C++ code, OR somehow-annotated-C++

For annotating C++, I suggest to try using C++ attributes, for example:
int x [[hare::encode_as("DELTA VLQ")]];

If NOT all target compilers support-and-ignore this syntax (yet?), we will need to resort to something like int x HAREATTR(encode_as("DELTA VLQ")), which will be #defined to empty string for those compilers which don't support it.

As for "how to implement it", there are two options:

a) parse C++ ourselves. One Issue (but a Big One): C++ parsing is ugly, but it MIGHT work in this case as we don't really need to parse function bodies(!), so most of grammar ambiguities will hopefully go away.
b) write it as a plugin to some-existing-C++-compiler (GCC/CLang). Issue 1: integrating with 3rd-party is always a headache. Issue 2: we need to make sure that plugin allows custom attributes as above. Issue 3: we will need to distribute this-3rd-party-compiler-with-our-plugin in pre-compiled form(!) at least for Win/Linux/Mac.

Which option to prefer - is unclear at the moment. All comments are very welcome. 

In any case, before doing anything, it is necessary to try the proposed attribute syntax on all three target compilers: MSVC, GCC, and Clang (ideally for us, compiler should accept the [[hare::...]] syntax above but ignore it).

**Comment by marcosbracco** [comment]
In my MSVC2015 `[[hare::something]]` gets a warning, but compiles fine.
`warning C5030: attribute 'hare::something' is not recognized`

I see two very different use cases that we may want to check.
1. The C++ code will be written to work with our tool from the very beginning. In this case we can be restrictive in accepting a limited _C++ subset_ (without macros or strange stuff), and we may parse this subset ourselves.
2. There is existing C++ code to be _migrated_ to work with our tool. This is a much more complex scenario, and success in parsing with a self written parser may not be achieved without some amount of refactoring.

Also in the pro / cons lists:
- Integration with existing 3rd-party is always a headache, but if integrated code is well maintained, once integration is done, a lots of complexity goes to other people.
- I have read around about how `clang` have been deliberately intended for 3rd-party integration (http://clang.llvm.org/docs/ExternalClangExamples.html). And there is documentation and samples about it. Have still not checked for `gcc`.

My general feeling is in favor of using 3rd-party. At least to try to use it and see how bad integration really goes. We should focus first on completing the cicle to build some minimal deliverable (also check legal), and not on adding features.
Maybe a couple of days to dig on gcc and clang to decide one or the other.
And then a week to test some basic integration and decide how it goes.

**Comment by nobugs-hare** [comment]
> In my MSVC2015 [[hare::something]] gets a warning, but compiles fine.
> warning C5030: attribute 'hare::something' is not recognised

A-ha. When playing with clang - try the same thing with it too.

> I see two very different use cases that we may want to check.

If we can pull it off - certainly scenario #2 will get us larger audience, so it is preferred (IF we can do it). 

> My general feeling is in favor of using 3rd-party. 
> 
> Maybe a couple of days to dig on gcc and clang to decide one or the other.
> And then a week to test some basic integration and decide how it goes.

Ok, let's try it this way. 

> (also check legal) 

Clang seems to be under BSD license (please double-check); if so - there are no problems. GCC is GPL, but it is (IIRC) under FSF copyright, and FSF has a long-standing position (TODO: double-check that it still stands) that it is ok to distribute their executables as long there is a process boundary between "us" and "them"; therefore, we MAY need to change the license for our-part-which-is-GCC-plugin, but that's about it. _all the analysis here is very preliminary, and is to be double-checked_ . Still, at the moment I don't envision fatal problems with either Clang or GCC, so feel free to find out whichever-integrates-better (and when you're ready to choose, then we'll take a closer look at the licensing for whichever-you-prefer).

**Comment by marcosbracco** [comment]
Seems GCC has some resistance to export the AST to be used by other tools.
https://lwn.net/Articles/629259/

In my opinion this tilts the balance in favor of clang as first candidate.

**Comment by nobugs-hare** [comment]
Ok, so clang it is :-)

**Comment by marcosbracco** [comment]
After some days with clang, I have found the following issues:
1. In clang, parser and type checks are kind of all-in-one. So I have not found some way to get a parsed AST without type-checks. This means that to parse:

```
#include <cstdint>
#include <string>
#include <vector>

class Item {
public:
    uint16_t id;
    std::string name;
    std::vector<std::string> data;
};
```

clang needs to find and include `<vector>` and `<string>` and all of related std includes. We can not just parse a partial piece of code. We need to give it a .cpp file (it will give you a warning if you try to compile just a header file, but it will work), and it will try to make all the includes and check all types.

It will work mostly out-of-the-box, since it has automatically detected my MSVC install and is using it, and from there getting the AST and working with it is dumb easy.

```
#include <...> search starts here:
 C:\Projects\o-log-n\llvm.org\build\Debug\bin\..\lib\clang\3.9.0\include
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
 C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt
 C:\Program Files (x86)\Windows Kits\8.1\include\shared
 C:\Program Files (x86)\Windows Kits\8.1\include\um
 C:\Program Files (x86)\Windows Kits\8.1\include\winrt
```

However, this is a lot more complex that just to parse a couple of structs on a header file. And is very hard to foresee how good will it work on clients.
The good side of this is when you already have a complex build environment with some `#define` and `#ifdef` and lots of headers files, you just can rest on clang resolving it right and giving us the right AST.
1. Attributes not know to clang report a warning (not a big deal), but are also dropped from AST. They just disappear. Apparently this can be work-arounded with GCC syntax `__attribute__((annotate("hare"))`

Aside from this two points that I haven't been able to figure out how to improve, the rest seems doable.

Comments are more than welcome!

**Comment by nobugs-hare** [comment]
> It will work mostly out-of-the-box, since it has automatically detected my MSVC install and is using it,

Do you mean it found #include dirs of MSVC - or more than that?

> And is very hard to foresee how good will it work on clients.

Can you elaborate?

> Apparently this can be work-arounded with GCC syntax **attribute**((annotate("hare"))

so that if we write it as `__attribute__((annotate("hareidl(whatever-we-want-here)"))`, you ARE able to get this  in clang? BTW, is it possible to make a kind of "plugin" to clang so that clang starts to "know" our attributes (and doesn't drop them anymore)?

> Aside from this two points that I haven't been able to figure out how to improve, the rest seems doable.

I will assume that the first point is about compiling the whole thing, and the second point is about using `__attribute__((annotate("hare(....)"))` instead of [[hare::xyz(...)]]. 

The first point is actually to be expected (in C++, parsing is interleaved with name resolution :-( ). And I don't see it as "too bad" for our purposes - the idea is to take a working-compilable-C++-program and to run our stuff over it, so it shouldn't be too bad (especially as Clang seems to be able to handle MSVC libs). 

The second point is not so bad too; it just means that we should make a macro (like HAREIDL("ENCODING DELTA")) which will be expanded as we need it (to an empty string for non-IDL compiles, and to, say `__attribute__((annotate("hare:ENCODING DELTA"))` for an IDL Clang compile). 

Overall, there are risks on this way (such as "whether Clang will continue to keep unknown GCC attributes in AST" - and that's why I'm asking about an "official" way to have a plugin within Clang), but if parsing-of-those-structs-we-need can be implemented in a reasonable time (like "some weeks") - why not?

**Comment by marcosbracco** [comment]
> > It will work mostly out-of-the-box, since it has automatically detected  
> > my MSVC install and is using it,
> 
> Do you mean it found #include dirs of MSVC - or more than that?

I mean #include dirs and libs from MSVC where automatically found and  
used. I am not really sure how (assume env vars), but clang did compile  
and link a native win32 .exe out-of-box.

> > And is very hard to foresee how good will it work on clients.
> 
> Can you elaborate?

My concern is about I had downloaded and built clang myself (no binary  
distribution).
I was thinking maybe a binary distribution may have some extra unknowns.
But probably it probably will work just as well. I can make a test.

> **attribute**((annotate("hareidl(whatever-we-want-here)")), you ARE able  
> to get this  in clang? BTW, is it possible to make a kind of "plugin" to  
> clang so that clang starts to "know" ouknowr attributes (and doesn't  
> drop them anymore)?

Probably, I will check this.

> Overall, there are risks on this way (such as "whether Clang will  
> continue to keep unknown GCC attributes in AST" - and that's why I'm  
> asking about an "official" way to have a plugin within Clang), but if  
> parsing-of-those-structs-we-need can be implemented in a reasonable time  
> (like "some weeks") - why not?

Yes, I think we can have it working in some weeks by using clang. And I  
also believe it will work very well for not-so-small projects where there  
may be a lot of compiler flags and defines and #ifdef kind of code, as  
clang can deal with all of its complexity.

**Comment by nobugs-hare** [comment]
Ok, let's start working on it this way, and see how it goes

Sergey

**Comment by marcosbracco** [comment]
Update on custom attributes.
While plugins don't seem to give a solution here, I have found simple (once you know where to touch :) to patch the source code to add our custom attributes. Two files changes, five lines of code each. clang rebuild required obviously.

Then code:

```
[[hare::nobugs]]
void hareFunc() {}
```

Dumps ast:

```
'-FunctionDecl 0xcd4570 <sample.cpp:22:1, col:18> col:6 hareFunc 'void (void)'
  |-CompoundStmt 0xcd4630 <col:17, col:18>
  '-HareSomethingAttr 0xcd45e0 <line:21:3, col:9>
```

Each attribute needs to be added individually (no `hare::*` support)
Attributes are described in tablegen language (a 'template' like syntax used internally a lot by clang to auto-generate source code)

```
def HareSomething : InheritableAttr {
  let Spellings = [CXX11<"hare","nobugs">];
  let Subjects = SubjectList<[Function], ErrorDiag>;
  let Documentation = [HareSomethingDocs];
}
```

**Comment by nobugs-hare** [comment]
> Update on custom attributes.
> While plugins don't seem to give a solution here, I have found simple (once you know where to touch :) to patch the source code to add our custom attributes. Two files changes, five lines of code each. clang rebuild required obviously.

Sounds good, but I suggest us to use syntax such as HAREIDL("ENCODING DELTA"), which can be #defined either to `__attribute__((annotate("hareidl(ENCODING DELTA)")` or to `[[hare::idl("ENCODING DELTA")]]` or to an empty string depending on the compiler and your implementation. How do you parse it - via hacking Clang to recognise our own [[hare::idl()]] or via GCC `__attribute__` in Clang - is up to you, but upper-level IMHO should be like HAREIDL("ENCODING DELTA") so that we're not too much relying on any specific implementation. 
1. How does it sound?
2. What do you think - would be it possible to generalise these 2_5 lines so that *anybody_ can insert their own attributes (ok, then it will become like 50 lines) and to submit these 2*5-50 lines as an official patch to Clang? If not feasible - we can live without it, but it would be much better to make a standard way of doing it (and to rely on this standard way)...

**Comment by marcosbracco** [comment]
> Sounds good, but I suggest us to use syntax such as HAREIDL("ENCODING  
> DELTA"), which can be #defined either to 1. How does it sound?

That's good.

> 1. What do you think - would be it possible to generalise these 2_5  
>    lines so that *anybody_ can insert their own attributes (ok, then it  
>    will become like 50 lines) and to submit these 2*5-50 lines as an  
>    official patch to Clang? If not feasible - we can live without it, but  
>    it would be much better to make a standard way of doing it (and to rely  
>    on this standard way)...

That would be great if doable, I will take a look after I get comfortable  
with current work-in-progress

I will be pushing a few changes, creating folder `/front/cpp-clang` for this. Code is not really important, but I would like to share some things on build process.
- I have added `cmake` for front/cpp-clang build generation, since llvm/clang use cmake, it makes easy to get all working. We will need to discuss if adding cmake for all our project, or how to make this work. In general I find cmake very useful, since it can generate MSVC project files, as weel as Makefiles, making development more platform agnostic.
- llvm/clang needs to be checkout at `Hare-IDL/3rdparty`, since they are quite big, I am not sure if adding a reference like we did with `cppformat` is a good idea or not.
- Currently I am working with llvm/clang `head`, but I think we will need to nail to specific release version(s).
- building llvm/clang requires adding include path to the build process (doing `#include "../../../some.h"` does not work). Luckily this is easy done with cmake.

**Comment by marcosbracco** [comment]
After too much time tring to build and link clang with our HareIDL tool, I have taken a slightly different approach.
I have created an small separate tool (I named it C++2HareIDL) that is build and linked with clang (inside clang build tree).
So, when HareIDL tool finds 

`MAPPING(Lang="C++") { FILE "abc.h" { CLASS XX; CLASS ZZ; } }`

it launches a separate process (with help of https://github.com/eidheim/tiny-process-library for platform independence) like following, and waits for its completion:

`C++2HareIDL -find-name=XX -find-name=ZZ abc.h`

This tool will parse the source file with help of clang libraries, will look for classes XX and ZZ, and will output (currently to stdout) idl code. HareIDL tool captures stdout and parses it, as if such idl was in such place at idl file (kind of #include it).

I will be pushing a working version of this code to branch `feature/C++2HareIDL` for you to review.
Build the C++2HareIDL tool is easy. Check out llvm/clang, apply our patch, build llvm/clang, tool gets built with the rest of clang. No compilation / linking issues.

I have not tested Linux yet (will do soon). Should work as nice as Windows.

Reasons behind this change:
- Building and linking with clang was problematic (Linux was still not working), and most important it was slowing down badly my development. Even when I had managed to make it work, it was going to be a source of trouble and pain in the future, clang is a too big project and our tool is small, clean and simple.
- This way of having separate tool, isolates clang complexity outside our code. C++2HareIDL tool is also very small.
- Development is way easier, and things flow much better (usually a good sign).
- If we ever need to support other languages, this pattern is easily extensible, using the same HareIDL with different tools for each language to be supported. Very likely is easier to use Java to make a Java parser, and so on, so different tool for each language makes sense.

@divanchykhin @nobugs-hare 
Please comment

**Comment by nobugs-hare** [comment]
No objections (as long as it works :-)). Actually, this two-process approach does indeed look more viable.

**Comment by marcosbracco** [comment]
I did some basic test on linux, and is working fine, so I will be closing this issue.
