### ISSUE TITLE
incorrectly reported KIND=PRIMITIVE for type Item

### ISSUE THREAD

**Issue by divanchykhin** [O-Log-N/Hare-IDL#51]
`PUBLISHABLE-STRUCT Character {`
 `// ...`
`SEQUENCE<Item> inventory;//Item is another PUBLISHABLE_STRUCT // defined elsewhere`
`};`

`inventory` is reported to have its DataType::kind to be PRIMITIVE while `Item` is not a standard type.

**Comment by marcosbracco** [comment]
Added PRIMITIVE vs NAMED_TYPE distinction.
Currently recognized PRIMITIVEs : INT8, INT16, INT32, UINT8, UINT16, UINT32
Let me know of other types to be added
