### ISSUE TITLE
PLEASE COMMENT: On primitive (and not-so-primitive) types in IDL

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#52]
We're facing quite a complicated question of "which primitive types we want to support?", and it is not as trivial as it looks. My suggestion in this regard is the following, PLEASE COMMENT.

I For IDL (which IS different from MAPPING):
I.1. there is a VERY LIMITED list of "base types":

```
- INTEGER[from,to] (or INTEGER(from,to], etc.). 
- FIXED-POINT[from,precision,to] (or FIXED-POINT(from,precision,to], etc.)
- FLOATING-POINT(significand_bits,exponent_bits)
- CHARACTER {list-of-allowed-UNICODE-values-and-ranges}
    for example CHARACTER {x20-x7e,xa0-xff} if ONLY Latin-1 symbols are allowed
    in the (distant) future we MAY additionally allow syntax like CHARACTER {"Latin-1","Latin-2"}, but not now for sure
- CHARACTER-STRING {list-of-allowed-UNICODE-values-and-ranges}
    and CHARACTER-STRING {list-of-allowed-UNICODE-values-and-ranges}[min_length,max_length]
- BIT-STRING[min_length,max_length]
```

I.2. all our usual types are introduced as TYPEDEFs of "base types". For example:

```
- INT32 is a typedef to INTEGER[-2147483648,2147483647]
- UINT32 is a typedef to INTEGER[0,4294967295]
- DOUBLE is a typedef to FLOATING_POINT(53,11)
- DOUBLE80 is a typedef to FLOATING_POINT(65,15)
- PRINTABLE-ASCII-STRING is a typedef to CHARACTER-STRING {32-126}
- UNICODE-STRING is a typedef to CHARACTER-STRING {1-1114111}
```

I.3 as a result, there should be NO such thing as INT32 etc. in our `class DataType` (only when corresponding Structure::declType == IDL); for Structure::declType == IDL the only primitive types allowed are INTEGER, FIXED_POINT, FLOATING_POINT, CHARACTER, CHARACTER_STRING, and BIT_STRING (and I propose to make them KINDs rather than type names, so that `name` field is always empty for non-NAMED_TYPE types within any Structure which has declType==IDL). 

II. MAPPINGs
For MAPPINGs things are a bit different, as we need to refer to language-specific stuff there. For MAPPINGs, KINDs are still the same (it is a job of the front-end to fill them in - for C/C++ it may be quite a headache BTW), BUT there is also a new non-empty `mapping_name` field indicating the name of the type in MAPPING target language (so that C++ uint32_t will look as kind=INTEGER (with appropriate limits), and mapping_name="uint32_t").

PLEASE COMMENT, this is going to have profound effect on our IDL. The idea is to avoid dealing with cross-mappings of all possible types at IDL/template level (like 32->64, int->uint, etc. etc.), replacing it with relatively simple maths around the parameters of INTEGER[] etc.

**Comment by divanchykhin** [comment]
Looks sane

**Comment by marcosbracco** [comment]
Looks good
I will make a branch for a quick first implementation, so we can play around and see how it works.

**Comment by divanchykhin** [comment]
What's about boolean?

**Comment by nobugs-hare** [comment]
RE: boolean. I am not sure whether it deserves a separate thing. If anything, I'd rather say it is a typedef to `ENUM { FALSE, TRUE };` What do you guys think?

**Comment by marcosbracco** [comment]
I pushed at branch `feature/issue-52` a sample implementation of primitives and DICTIONARY for review.
Not supported yet **character class** for CHARACTER or CHARACTER-STRING, nor typedefs (will try to have a couple of them today).
https://github.com/O-Log-N/Hare-IDL/blob/feature/issue-52/src/front/idl/test/sample.idl#L22

I feel that boolean should be a first class citizen and not a typedef, but I really don't have rationale, just a feeling.

**Comment by divanchykhin** [comment]
Hi Marcos,I looked at code mostly - it looks sane at the first glance,but I failed to merge quickly, so I have not able to compile and see what's going on practically.As a bottom line: please merge... chances it's working and suitable are far non-zero.Regards,D.I.

-------- Original Message --------
Subject: Re: [Hare-IDL] PLEASE COMMENT: On primitive (and
not-so-primitive) types in IDL (#52)

**Comment by marcosbracco** [comment]
Merged into `develop`

**Comment by marcosbracco** [comment]
`DataType::PRIMITIVE` and `DataType::LIMITED_PRIMITIVE` will be dropped after migration

**Comment by marcosbracco** [comment]
I have added a tentative `class CharacterSet` and `class CharacterRange` to `front-back/idl_tree.h`
Also added related support to parser:

```
CHARACTER{ 1-126 }
CHARACTER{ 1-99, 100, 101-124, 125, 126 }
```

Only decimal (not hex) supported. Sets will be compressed, so both sets in previous example are equivalent. Also support named character set:

```
CHARACTER-STRING{"PRINTABLE-ASCII"}
CHARACTER-STRING{"UNICODE"}
```

Currently only this two names are supported, and provide symmetry with `PRINTABLE-ASCII-STRING` and `UNICODE-STRING`
Comments are welcome

**Comment by marcosbracco** [comment]
This is mostly working, closing this.
