### ISSUE TITLE
Type restriction on SEQUENCE and DICTIONARY 

### ISSUE THREAD

**Issue by marcosbracco** [O-Log-N/Hare-IDL#53]
I have currently removed all type restrictions on SEQUENCE and DICTIONARY.
I can not find it know, but there was a comment somewhere about SEQUENCE shuld not be allowed to have a SEQUENCE as paramType, but a `typedef` should be created by front, to make life of back easier. Does this still hold?
Or is ok for DICTIONARY key to be another DICTIONARY?
Please let me know if any kind of restriction is curerently needed for SEQUENCE and DICTIONARY types.

**Comment by nobugs-hare** [comment]
> Does this still hold?

Let's ignore it for now. Then we'll have two options: a) front to remove
recursive collections, b) front to remove typedefs.

Sergey

**Comment by marcosbracco** [comment]
Closing this.
