### ISSUE TITLE
/front/visitor.h - consider removing

### ISSUE THREAD

**Issue by nobugs-hare** [O-Log-N/Hare-IDL#9]
It _seems_ that visitor.h stuff (including all kinds of traversing) is not going to be a part of the /front/; if so - let's remove it

**Comment by marcosbracco** [comment]
@divanchykhin do you have plans on how you will do the tree trasversal at /back/ ?
On the 'visitor' pattern, you will be creating a class derived from 'NodeVisitor' and implementing its methods. I can share some samples of how this is done. Is a very clean way of doing it, but not always fit perfect to the needs.
If you don't plan to use any of them, I can remove visitor support code from /front/
If you don't have made up your mind on this yet, I will keep them for some time

**Comment by marcosbracco** [comment]
As we have defined our exchange tree format, this issue currently internal to /front/.
I will decide its faith in the near future
